backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# These lines should *not* be indented
media_folder: "static/assets/img/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    filter:
      field: published
      value: true
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Excerpt", name: "description", widget: "string"}
      - {label: "Canonical URL", name: "canonical_url", widget: "boolean", default: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
      - {label: "Featured Image", name: "cover_image", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list"}
